### ISSUE TITLE
Laravel Octane compatibility

### ISSUE THREAD

**Issue by ibrunotome** [lorisleiva/laravel-actions#121]
It looks like it's necessary to use one `$app` instance for each request instead of `$this->app` and maybe there is more changes.

https://twitter.com/troelsjohnsen/status/1379114592140455943

Have you already used it before?

**Comment by lorisleiva** [comment]
Hi there 👋 

I've tagged a new release that *should* be ready for Octane: [`v2.1.5`](https://github.com/lorisleiva/laravel-actions/releases/tag/v2.1.5).

I've basically made sure Laravel Actions always accesses the container and the request on demand.

Since I don't have any Octane application running, it'll be great if someone could test that out for me and let me know if everything works as expected. 🙂

**Comment by lorisleiva** [comment]
I'll close this for now but I'm happy to reopen if there are any issues with Octane.
