### ISSUE TITLE
Route Model Binding returns new model instance without attributes

### ISSUE THREAD

**Issue by leandrodiogenes** [lorisleiva/laravel-actions#130]
I'm sorry if this is a question that has already been clarified, but I couldn't find the result. 
I believe that a new instance of the model is being returned to the method;
Im using `laravel` v8.54 , `php` v7.4.5 and `laravel-actions` v2.1
```php
<?php
namespace App\Actions;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Router;
use Lorisleiva\Actions\Concerns\AsAction;
use Lorisleiva\Actions\Concerns\WithAttributes;

class TestUserAction {
    use AsAction;
    use WithAttributes;

    public static function routes(Router $router){
        $router->get('api/users/{user}',static::class);
    }

    public function asController(User $user, Request $request) {
        $this->fillFromRequest($request);
        return [
            'user' => $user,
            'user_using_find' => User::first(),
            'filled_attributes' => $this->all()
        ];
    }
}

```

![image](https://user-images.githubusercontent.com/2463299/129827569-d900825d-a950-4ecc-86a7-2e99585f30de.png)
![image](https://user-images.githubusercontent.com/2463299/129827828-3630e83d-5dc3-4867-a165-e44f40a65f88.png)

**Comment by lorisleiva** [comment]
Hi there 👋 

Good catch! It looks like route model binding is failing when using the `WithAttributes` trait. I'll add a regression test for this and try to see where the error is coming from.

**Comment by lorisleiva** [comment]
Hiya! I added a regression test today (6e0aa6ed7cf379c3dd0e8d842a1ce754394152f6) but unfortunately I cannot reproduce the issue. Are you sure your route (or route group) is using the `SubstituteBindings` middleware? It should come by default in the `web` and `api` middleware groups.

**Comment by leandrodiogenes** [comment]
Hi hi, thanks for reply. 
The action works fine when registered by default method `(routes/api.php)`.
But there is the problem, i need to add `SubstituteBindings` middleware manually on all actions to make work when registered direct on actions.
```php
public static function routes(Router $router){
    $router->get('api/users/{user}',static::class)->middleware([SubstituteBindings::class]);
}
```
or 
```php
public function getControllerMiddleware(): array {
    return [SubstituteBindings::class];
}
```

Do you have another better solution?
What i`m doing wrong?

I`m using the default middlewares of laravel and the middleware is present on group middlewares.

```php
protected $middlewareGroups = [
    'web' => [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        // \Illuminate\Session\Middleware\AuthenticateSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],

    'api' => [
        // \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
        'throttle:api',
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ],
];
```

**Comment by leandrodiogenes** [comment]
Another alternative was register the action routes grouped and apply the middleware group manually on my service provider.

But there is the point.
The middleware group its not registered by default on action routes.
To register with api group middleware of laravel, i need to do someting like that?
```php
Route::prefix('api')
    ->middleware('api')
    ->group(function() {
        Actions::registerRoutes();
    });
```

**Comment by lorisleiva** [comment]
Hi, oh okay that makes sense now.

Yeah sadly, we can't make the decision for the developer because they could use actions with the `web` or `api` middleware group or anything else that's custom. If you only register your actions as API endpoints then your latest example is probably the best thing to do.

Otherwise, you'd have to manually add `->middleware(['api'])` to your route definition which would give you the flexibility to use either.

Note that, whilst the `routes()` method is supported due to popular demand, it has a few caveats which is why I don't use that feature myself. Aside from the one you've mentioned in this issue, you also can't control the order in which your routes are registered. Most of the time, that's fine but if you have a route with a parameter like `articles/{id}` and another with an explicit segment like `article/create`, you'd always want to make sure the latter gets registered before the former.

When registering routes using the `routes()` method, these routes will be loaded by alphabetical order of your classes FQNS which may create unpredictable results.
