### ISSUE TITLE
ActionRequest not injected in authorize method if called directly

### ISSUE THREAD

**Issue by davidjr82** [lorisleiva/laravel-actions#135]
Hi!

When using WithAttributes trait, if I call `$this->validateAttributes();` it will inject the ActionRequest in the authorize method:

`public function authorize(ActionRequest $request): bool` ...

but I want to call directly to authorize without validating attributes. In this case, ActionRequest is not being injected. Would it be possible?

Why I want to call authorize without validating? Because I am trying to use the action to show the form as it says here in the docs: [routes-with-explicit-methods](https://laravelactions.com/2.x/register-as-controller.html#routes-with-explicit-methods). Therefore I want to check the athorization to show the form, but without any validation because I am not going to call to handle method.

Also, when I call authorize from the "showForm" method it only returns boolean (as expected), so I have to call it with an abort_unless helper. Is there any way to call it in the "request authorize" way so it throws the exception directly if it return false?

By the way, I find this feature really useful, so I would remove the sentence `On some rare occasions...` in the docs! :)

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for the detailed explanation of this issue and what you are trying to achieve.

When using the "WithAttributes" trait, validation should no longer happen automatically on the action and it has to be explicitly triggered using the "validateAttributes" method. When you do all validating methods such as "authorize", "rules", etc. will be used.

So I think there might be a bug here because the "authorize" method should never be called unless the "validateAttributes" method is called (which should ensure proper dependency injection).

Something else that confuses me is how do you plan on reusing the same validation methods (authorize, rules, etc.) for both the "showForm" method and the "handle" method? Because when calling "validateAttributes" both methods will be using the same validation logic which might not be the desired outcome.

Regarding the authorize Boolean, you can also provide a "Access\Response" object instead if you want to provide more info (see [documentation](https://laravelactions.com/2.x/add-validation-to-controllers.html#authorization)).

Fair enough, I'll make sure to update the unhelpful "rare" from the docs haha.

**Comment by davidjr82** [comment]
Hi Loris!

So I am going to talk to my actual implementation to give an insight of how I am using it. I have a users table, where it display all users to an admin user. From there, there is an "Active/Disabled" column that shows a button saying if the user is active or not.

If I click the button, it will send a form post to an action, that toggles the user is_active column. As a response, it will give the html for that tiny form only (I have one form per user active column in the table).

But also, it would happen that from other browser, other admin can disable a user, so the form will listen the broadcasting, and will trigger a reload of that single form. To do that, I am using the exact same action, because it make sense to me to store the update logic and the tiny form in the same place.

Here comes the thing. To call handle I need to validate some data (well in my exact case this is not truth, but it could be the I need to validated that the data in the post values are what I need to actually update the user). But to show the user in the form, I only need the user id and check if the $request->user() is in fact an admin user.

- handle => needs data validation to make the actual update. 
- showForm => needs to check only if the current user is an admin to show the form to update the user

I would keep allowing to call authorize from other places apart the validateAttributes, because is helpful and it doesn't disturb the validation process. 

Does it make sense?

**Comment by lorisleiva** [comment]
Okay so I understand your use-case but I'm struggling to see the issue haha. Would something like this not work?

```php
class MyAction
{
    use AsAction;
    use WithAttributes;

    public function authorize() { /* ... */ }
    public function rules() { /* ... */ }

    public function showForm(Request $request)
    {
        // Goes through authorization only.
        if (! $this->authorize($request->user())) {
            abort(401);
        }

        // ...
    }

    public function handle()
    {
        // Goes through authorization and data validation.
        $this->validateAttributes();

        // ...
    }
}
```

Also note that you can access the validator via `Lorisleiva\Actions\AttributeValidator::for($this)` which make me think it would be nice to have some syntactic sugar for it and also being able to call additional public methods such as `authorizeOnly` and `validateWithoutAuthorizing` or something like that.

**Comment by davidjr82** [comment]
Hi Loris!

We can close this one because as you said, it is not a bug. It was me that I thought that authorize method was going to use DI, but it can be called as you said.

Thanks a lot for this great package!
