### ISSUE TITLE
execute validation before authorization

### ISSUE THREAD

**Issue by deviouspk** [lorisleiva/laravel-actions#14]
Hi,

I think it makes more sense to execute the method

> $this->resolveValidation();

before the
> $this->resolveAuthorization();

Since you often need to rely on the input to do an authorization.

Can we switch these methods? like this:

```
    public function run(array $attributes = [])
    {
        $this->fill($attributes);
        $this->resolveBeforeHook();
        $this->resolveValidation();
        $this->resolveAuthorization();

        return $this->resolveAndCall($this, 'handle');
    }
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Resolving authorization before validation is how Laravel resolves Request objects so I want to carry on following that convention.

It also makes more logical sense since you want to make sure the user is allowed to perform a certain action before evaluating the data they provide.

Note that you can access all attributes of the action in the `authorize` method (just like you would in the `handle` method) so there should not be any issues with missing input.

**Comment by mortenscheel** [comment]
I think this is worth reconsidering.

I would like to be able to use my Policies in the `authorize` method, to check if the user has access to the model ids provided in the attributes. But in order to do that, I would have to validate all the inputs manually, making the validation step redundant.

I don't see why it would be dangerous to validate the attributes before authorization. I know Laravel's `FormRequest` does it in the same order, and it's the only reason I don't use them more often. I mean sure, I can perform my policy checks after the validation is passed - but then what's the point of having an authorize method? Or am I misunderstanding the purpose of the `authorize` methods?

**Comment by lorisleiva** [comment]
I understand your point but fundamentally, it is expected of an API to start by making sure a user is allowed to perform an action before we validate the payload of the request. Changing this will cause breaking changes and confusion to other users.

Typically, you would only ever need the authenticated user and the main resource being handled to compute that logic. The latter being passed as a URL parameter instead of request attribute, should be accessible in your authorize method. For example, if you want to authorise a user updating a blog post, you might have the following route: `PUT /posts/{post}`. Therefore you have all you need (I.e. a user and a post) to determine if this action is authorised.

Yes, in some cases we might need some additional authorisation logic that  depends on validated data. In which case, I typically write that logic in an `afterValidator` callback and either add the error to the validator’s error bag (therefore throwing a 422) or, when needed, I throw a `400` directly.

Note that I like throwing a `400` instead of a `403` in these cases to make sure my application throws erroneous status codes in the following order: 

1. 401 — should be authenticated
2. 404 — should exist
3. 403 — should be allowed to perform this action (or 404 as well if you want to obfuscate URL discovery like GitHub does)
4. 422 — should have valid data
5. 400 — any other errors coming from the client

(Btw, I will write back to your other posts today, thank you for your patience 🙂)

**Comment by kmbt** [comment]
Hi, I have come across a similar need as described, which is doing some business-logic, and data-integrity checks before actually 'handling' the action. For that, I needed to have my input arguments validated.

I have finally settled on using `afterValidator` callback (as mentioned by @lorisleiva ) with:
```
        if ($validator->failed()) {
            return;
        }
```
I think that for specific project needs the `Action` class could be easily extended to support three levels of validation:
1. Authorization
2. Data validation
3. Business logic validation
And that could be also achieved by overriding `afterValidator` to resolve and call some business logic validation method.

**Comment by kmbt** [comment]
This could be encapsulated in a trait like so:

```
trait ValidatesBusinessLogic
{
    public function afterValidator($validator)
    {
        if ($validator->errors()->isNotEmpty()) {
            return;
        }
        $this->resolveAndCall($this, 'validateBusinessLogic');
    }

    abstract public function validateBusinessLogic();
}
```
