### ISSUE TITLE
Class App\Listeners\EventListener does not exist

### ISSUE THREAD

**Issue by ethanclevenger91** [lorisleiva/laravel-actions#24]
Not sure why this is popping up. Fatal error appears after running `composer require...`. Rest of composer.json below:

```
"php": ">=7.1.3",
"laravel/framework": "5.7.*",
"ramsey/uuid": "^3.0.0",
"doctrine/dbal": "^2.5",
"league/fractal": "^0.17.0",
"laravel/tinker": "^1.0",
"fideloper/proxy": "^4.0"
```

**Comment by lorisleiva** [comment]
Hmm... That can’t be right. This class doesn’t make any sense and we’re not using or assuming the user is using anything like that on Laravel Action. Perhaps you’ve uncommented something in your EventServiceProvider?

If not, can you provide the steps required to reproduce the error from a fresh Laravel install?

**Comment by FallenNoir** [comment]
@ethanclevenger91 
I think it happened because of a leftover of some older Laravel installation.
I'm unsure why the package is sensitive to that, but please check out app\Providers\EventServiceProvider.php
if you have there these:
`
protected $listen = [
    'App\Events\Event' => [
        'App\Listeners\EventListener',
    ],
];
`
If you don't have those files (you probably don't), just remove them.
