### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by jaulz** [lorisleiva/laravel-actions#276]
Unfortunately, the website is not available anymore. Is there any alternative way to see the documentation? 😊

**Comment by lorisleiva** [comment]
Ugh looks like Netlify blocked my account for no reasons. I've sent them a support ticket. Thanks for letting me know! 🙏

**Comment by lorisleiva** [comment]
Typically I'm afk this weekend but I'll move the documentation to Vercel on Monday if Netlify hasn't sorted this out by then.

**Comment by lorisleiva** [comment]
Okay, I've migrated to Vercel and updated the DNS settings. It should take a little while to propagate but you can use [laravel-actions-docs.vercel.app](https://laravel-actions-docs.vercel.app/) in the meantime.

P.S.: I'm never using Netlify again. They blocked my account and thus **killed all the production websites** I had deployed there on a whim because they flagged one of the websites as having a copyright issue (which is wrong). They did not give me any prior notice so I could explain the situation nor did they warn me that they'd blocked my account. Their customer support is borderline inexistent so I've been monologuing all weekend and they've done nothing about it.

**Comment by jaulz** [comment]
Thanks a lot for your quick reaction and sorry for the pain 😬
