### ISSUE TITLE
$timeout not respected when running Actions as Jobs 

### ISSUE THREAD

**Issue by javis** [lorisleiva/laravel-actions#28]
When running actions as jobs, `public $timeout` defined inside the class, doesn't seem to be respected by the worker

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for reporting this. I'll do some digging asap.

**Comment by lorisleiva** [comment]
So I've looked at all the jobs dependencies and I don't see why this would happen. Could you please try to set the `public timeout` property inside a regular Laravel job to see if that works?

**Comment by javis** [comment]
Cool! plz keep me updated! 

In the meantime, I will use Jobs instead.

thanks!

**Comment by lorisleiva** [comment]
Hi @javis, I've updated the Bus Dispatcher so that it uses the **action** directly as a **handler**. That way any property defined on the action like `$timeout` should be used by the job dispatcher.

All tests are passing but could you please use `dev-master` and let me know if it works for you before I create a new release?

Thanks again for your help on this issue. 🙂

**Comment by javis** [comment]
OK! Today I'll try that!

**Comment by javis** [comment]
It works fine now :D 
Thanks!

**Comment by lorisleiva** [comment]
Perfect, thanks for double-checking for me. 

🚀 This has been released in [`v0.2.4`](https://github.com/lorisleiva/laravel-actions/releases/tag/v0.2.4).
