### ISSUE TITLE
Route Model Binding returns new Model instance instead of null

### ISSUE THREAD

**Issue by huy-tran** [lorisleiva/laravel-actions#45]
I am using the latest version of this awesome package and have a question if the Route Model Binding can return new Model instance instead of `null`. 

The reason because when we type-hinting the Model we expect to retrieve that Model even if it does not exist. Let's think of the NullObject pattern. By doing this inside the action logic we don't need to check whether the Model is null.

Currently, I am doing the following:
```
public function handle(User $user, ?Role $role): User
{
        $user->update([
                'role_id' => optional($role)->id
                // could be more checks for other attributes/models
        ]);

        // Potentially check more afterwards

        return $user;
}
```
I am happy to submit the simple pull request if you guys consider this question.

Thanks again for this great package!

**Comment by lorisleiva** [comment]
Hi there 👋 

Currently, if the model does not exist, the Route Model Binding works like this:

- Typehint `Role $role` → throws a `ModelNotFoundException`
- Typehint `?Role $role` → returns `null`

If I understand correctly, you'd like the Route Model Binding to work like this:

- Typehint `Role $role` → throws a `ModelNotFoundException`
- Typehint `?Role $role` → returns `new Role()` (i.e. an empty model)

I'm afraid I don't think this is a relevant use case for most people and it removes flexibility instead of adding some.

If you'd like to follow the NullObject pattern instead of using null, I would suggest adding this one line at the top of your action handler:

```php
public function handle(User $user, ?Role $role): User
{
    $role = $role ?? new NullRole();

    // ...
}
```

I hope this helps. 🍀

**Comment by huy-tran** [comment]
Hi @lorisleiva ,

Thanks for considering my question and you understand my question correctly. For the moment I agree with your suggestion. 😄 

Cheers!
