### ISSUE TITLE
Define available methods on base Action class

### ISSUE THREAD

**Issue by mortenscheel** [lorisleiva/laravel-actions#49]
A lot of optional methods don't exist on the base Action, and are only called if a `method_exists('methodNameAsMagicString')` check returns true.

This makes it impossible for an IDE like phpStorm to know that these methods are available, so they're not listed when searching for methods, or using the `Override Methods` tool. 

If it's possible, I suggest defining all available methods on the `Action` class, preferably with PHPDocs describing argument types and return type.

I won't mind creating a pull request if you're interested.

**Comment by lorisleiva** [comment]
Hi there 👋 

I wish I could but unfortunately, this is necessary to resolve the arguments of each method dynamically in order to support dependency injections.

If I pre-define these methods in the abstract class, you will no longer be able to provide your own custom signatures.

Even defining these methods as Docblock annotations will throw some warnings in your IDE.

**Comment by mortenscheel** [comment]
Oh, I see. To be honest I don't know a whole lot about how dependency injection works behind the scenes.
