### ISSUE TITLE
How to mock when running the action?

### ISSUE THREAD

**Issue by ArtisanTinkerer** [lorisleiva/laravel-actions#63]
Hi,

Is there anyway to mock an action when using it like this:
```
$other = ActionName::run([
            'country' => 'US'
        ]);
```

(This creates an instance of the action, instead of a mocked version)

It works if I do this:

```
$test = app(ActionName::class);
```
 
This is where I setup the mock:

```
  $this->instance(ActionName::class, Mockery::mock(ActionName::class, function ($mock) {
	   $mock->shouldReceive('run')->once()->with(['country' => 'US'])->andReturn('123456');
   }));

```

**Comment by lorisleiva** [comment]
Hi there 👋 

Good point, that wouldn't work since the static `run` does not call the container.

https://github.com/lorisleiva/laravel-actions/blob/ef190a20c2d270d1907e2df612a20a2eb8d19dfa/src/Action.php#L208-L215

Replacing this such that it does resolve from the container and maybe even provide some helper static methods like `fake` would be an awesome addition to Laravel Action.

**Comment by lorisleiva** [comment]
This is now available on v2. 🚀 

https://laravelactions.com/2.x/mock-and-test.html
