### ISSUE TITLE
[2.0] Register routes directly in Actions

### ISSUE THREAD

**Issue by jalt007** [lorisleiva/laravel-actions#77]
Hello & happy new year!

I noticed that v2 doesn't yet have the ability to define routes inside the action; #3.

Your `routes(Router $route)` hook implementation was spot on IMO.

> For context I'm a heavy user of this... to the point where `routes/web.php` is empty!

I was interested to hear your stance on this being included in v2?

**Comment by lorisleiva** [comment]
Hey 👋  Happy new year to you too! 🥳 

I'm glad you raised this issue because tbh I wasn't sure how popular this feature was or if it was used by anyone at all.

For now, it's been removed from v2 but it's not final. First of all, here's the reason why:

On v1, we couldn't just register an action as a command in the console Kernel because it would have had to be an instance of the Symfony `Command` and all the baggage it comes with. Instead, we were wrapping it in a closure and registering it in a Service Provider. That means, our application needed to know about all our actions for this to work. Therefore, we had route registration for free.

On v2, there's none of that anymore. Everything is resolved in real-time from the container using a special interceptor and then wrapped in a decorator based on the pattern that was identified. E.g. `ControllerDecorator`, `CommandDecorator` and so on. This is much cleaner and much less intrusive to the point that Laravel Actions no longer need to override any core components to work and our application (i.e. service providers) no longer needs to know about our actions. Therefore, we no longer have route registration for free.

The cost of adding this feature back is that we need to add some sort of call in a service provider that tells the package where the actions are located (default to `app/Actions`) and recursively go through all of their `routes` method at runtime.

I'm still somehow convinced that most people are using routes files (because I am haha) so I wouldn't want to do that by default (now that it's no longer a necessity) but I could implement some sort of `Actions::registerRoutes($optionalPath)` method that would allow you to keep registering these routes in the action directly.

What do you think? 🙂

**Comment by jalt007** [comment]
Appreciate the detailed insight on this angle into v2 👌

> I wasn't sure how popular this feature was or if it was used by anyone
> ...
> I'm still somehow convinced that most people are using routes files

Yeah I'd imagine the vast majority still use routes files!

I've bought into the "unit of life" value (being able to look at an action file & have everything present to understand whats going on) of it as you explained in https://github.com/lorisleiva/laravel-actions/issues/3#issuecomment-497476414. Plus in my projects:

- A naming convention that fits in nicely with [inertia.js](https://inertiajs.com/) e.g:
  - Route `name('pages.index')` defined in -> `App\Actions\Pages\Index.php` -> inertia response to page component -> `resources/js/Pages/Index.vue`
- `php artisan route:list` fills in for other route visibility needs.
- `php artisan route:cache` in production nullifies any negative runtime performance impact

> I could implement some sort of `Actions::registerRoutes($optionalPath)` method that would allow you to keep registering these routes in the action directly.

This would be really nice if its not too much of a hassle. Though if you don't want it part of the package it looks like something I could handle manually in own projects.

**Comment by lorisleiva** [comment]
These are 100% valid points and tbh it pains me to lose any feature on v2.

I'll work on it once I finish the documentation. I've got a little backlog of things to do before I release it so I'll add this to the list. Until then I'll leave this issue open.

Thanks again for the feedback. If you happen to be playing with v2 before its release don't hesitate to open up a new issue and share your thoughts. I'd love to hear them.

**Comment by lorisleiva** [comment]
Added and [documented](https://deploy-preview-7--laravel-actions.netlify.app/2.x/register-as-controller.html#registering-routes-directly-in-the-action) on the `next` branches. 🚀 

I'm hoping to finish up the documentation today so v2 should be out very soon. 🤞

**Comment by jalt007** [comment]
👌 Great work, thanks!!
