### ISSUE TITLE
AsJob JobDecorator param

### ISSUE THREAD

**Issue by exodusanto** [lorisleiva/laravel-actions#82]
If I need to use the `JobDecorator` inside the `asJob`?

This is an example to check if a job is inside a batch and if batch is available

```php

    public function asJob($user): void
    {
        if ($this->batch() && $this->batch()->cancelled()) {
            return;
        }

        $this->handle(User::find($user));
    }
```

Maybe it can be solved as `AsController` with the injection of `Request`, in this case the Job configuration

_Originally posted by @exodusanto in https://github.com/lorisleiva/laravel-actions/issues/81#issuecomment-757225262_

**Comment by lorisleiva** [comment]
Hey, thanks for opening it as a new issue. 🙇‍♂️ 

Yes I spotted that when adding support for `Batchable` and I want to support it but I'm still not 100% happy with all the solutions I come up with.

Users will expect the `asController` method to support dependency injections (since this is how it works for controllers) but they will expect `asJob` to reliably contain the parameters provided when dispatching the job.

I even thought of `asJobWithBatch(Batch $batch, ...$jobParameters)` but I don't find that very elegant.

I'm thinking of injecting a reference of the `JobDecorator` inside the action itself by using a property like `$laravelActionsJobDecorator` (to avoid conflicts) and then have a `batch()` helper method delegating to it: `$this->laravelActionsJobDecorator->batch()`. But I really want Laravel Actions to be as little intrusive as possible so I'm still looking for a better way.

I'll work on that tomorrow. I just need to sleep on it I think. 😊

**Comment by exodusanto** [comment]
Yes the reference at `$this` can be a solution but maybe this will broke the new design patter, like the `$this->request` was removed in v2.

So in my opinion a `asJobWithBatch` can be the solution but there is the problem of code duplication between `asJob` and `asJobWithBatch`.

Maybe this will fit most of use case:
```php
asJob(JobDecorator $job, ...$jobParameters)
```

**Comment by lorisleiva** [comment]
You're right, `asJob` is cleaner. I've decided to use `Reflection` to inject the `?Batch` or the `JobDecorator` on the first argument if and only if it is requests.

```php
// Without injecting.
public function asJob($foo, $bar)
{
    // ...
}

// Injecting the batch.
public function asJob(?Batch $batch, $foo, $bar)
{
    // ...
}

// Injecting the decorator.
public function asJob(JobDecorator $job, $foo, $bar)
{
    // ...
}
```

It's released as [`v2.0.4`](https://github.com/lorisleiva/laravel-actions/releases/tag/v2.0.4) and [documented here](https://laravelactions.com/2.x/dispatch-jobs.html#batching-jobs). 🚀 

Again I've added tests but if you could confirm that it works for me, that'd be much appreciated. 🙂

**Comment by exodusanto** [comment]
Updated my application logic using directly the action without a middle Job and works like a charm 🚀

**Comment by fjarrett** [comment]
@exodusanto @lorisleiva Hey there 👋  Thanks for this amazing library! I stumbled across this issue as I've been struggling to figure out exactly how this feature works when dispatching an action.

Upon further reading [in the docs](https://laravelactions.com/2.x/dispatch-jobs.html#batching-jobs), this feature might only apply to batches, but it seems like any job could benefit from accessing the methods provided by `InteractsWithQueue` to manipulate the job. Unless I am misunderstanding how to do this? Happy to open a separate issue if this comment resonates.

### Example

Sometimes you may want to handle a job differently depending on the Exception, like releasing it back the queue in some cases and failing immediately in others. Consider the following...

```php
<?php

namespace App\Actions;

use App\Models\User;
use Lorisleiva\Actions\Concerns\AsAction;
use Lorisleiva\Actions\Decorators\JobDecorator;

class MyAction
{
    use AsAction;

    public $jobTries = 10;

    public function handle(User $user)
    {
        if ($user->isAdmin()) {
            throw new \Exception('Action never allowed for Admin users.', 911);
        }

        // ...
    }

    public function asJob(JobDecorator $job, User $user)
    {
        try {
            $this->handle($user);
        } catch (\Exception $e) {
            if ($e->getCode() === 911) {
                $job->fail($e);
            } else {
                $job->release(5); // Delay retry for 5 seconds.
            }
        }
    }
}
```

Then dispatching the job by calling this:

```php
App\Actions\MyAction::dispatchSync($user);
```

Results in a `TypeError`:

```
TypeError: App\Actions\MyAction::asJob(): Argument #1 ($job) must be of type Lorisleiva\Actions\Decorators\JobDecorator, App\Models\User given
```

Presumably because the Reflection detection only works for batches?

**Comment by exodusanto** [comment]
Hi @fjarrett

> Presumably because the Reflection detection only works for batches?
More like it detect all Job types (Job, Batches, Chain)

I think that is the `dispatchSync`, with a `dispatch` you have the same error? 
`dispatchSync` is same behavior of `run` in this case.
