### ISSUE TITLE
Validate when using as an object

### ISSUE THREAD

**Issue by Wulfheart** [lorisleiva/laravel-actions#83]
Is it possible to validate before calling the handle method?

**Comment by lorisleiva** [comment]
Hi there 👋 

No, authorisation and validation is now only applied when an action is executed as a controller. It used to be possible in v1 because the package was very opinionated and forced you to use a unified set of attributes no matter how you ran your action.

Laravel Actions v2 aims to let you define your actions without getting in the way and therefore, there's no longer a set of attributes to validate when running as anything else than a controller.
