### ISSUE TITLE
Caching issue with shared validator caching

### ISSUE THREAD

**Issue by williamjulianvicary** [lorisleiva/laravel-actions#84]
Hey Loris,

Ran into an error when testing actions as controllers, the flagged line below (while with good intention!) is failing when the `rules()` that are being defined utilise request input (unique validation exclusions in our case) when testing the same endpoint expecting a different validator.

https://github.com/lorisleiva/laravel-actions/blob/995429aad9fc2511b61e991c8512ae729e4f47be/src/ActionRequest.php#L40

Hopefully, that's straightforward enough - essentially the validator instance shouldn't be cached (and/or allow rules to change across multiple requests) as when testing the same endpoint multiple times, the caching of the validator causes the unique rules to fail.

Lemme know if you need an example!

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for reporting this, I've added a test and I could indeed see that validation was being cached after failures.

The issue was that the `ActionRequest` was only being removed from the container if everything went well. I've fixed this and released it as `v2.0.5`.

Thanks again for the bug report. 🙇‍♂️

**Comment by williamjulianvicary** [comment]
Thanks @lorisleiva!
