### ISSUE TITLE
Installation via composer throws illuminate/contracts conflict error

### ISSUE THREAD

**Issue by wocodes** [lorisleiva/laravel-actions#94]
On a fresh laravel 7 installation (precisely 7.29.0), installing this package via composer fails due to a clash of illuminate/contracts require...

Below is a sample error:

> $ composer require lorisleiva/laravel-actions
> 
> Using version ^2.0 for lorisleiva/laravel-actions
> ./composer.json has been updated
> Running composer update lorisleiva/laravel-actions
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - lorisleiva/laravel-actions[v2.0.0, ..., v2.0.7] require illuminate/contracts ^8.15 -> found illuminate/contracts[v8.15.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
>     - Root composer.json requires lorisleiva/laravel-actions ^2.0 -> satisfiable by lorisleiva/laravel-actions[v2.0.0, ..., v2.0.7].
> 
>

**Comment by lorisleiva** [comment]
Hi there 👋 

That's because Laravel Actions v2 can only work from Laravel v8.15 and above ([Click here for the why if you're interested](https://laravelactions.com/2.x/how-does-it-work.html#identifying-how-an-action-is-being-executed)).

On a Laravel 7 application you would need to use Laravel Actions v1.
