### ISSUE TITLE
How would you validate your data if is run as object

### ISSUE THREAD

**Issue by anyb1s** [lorisleiva/laravel-actions#97]
An action like AddTimesheetEntry which is generic and could be called from either api/web (as controller)
or like livewire method call should always validate it's data.
With the approach without attributes how would be best to the validation?
My thinking is to add the checks within the handle method and throw the necessary exceptions. Is it is a good idea to run a validator inside the handle() method because it wont be run automatically as object?

E.g. in livewire method 
public function addTimesheetEntry() {
  AddTimesheetEntry::run(date, user, ...other args)
}

Currently this on my end runs validation as of v1, but not sure what would be best approach for v2?
Can you help with advice what would be better to upgrade.

**Comment by lorisleiva** [comment]
Hi there 👋 

First of all, I've received a lot of feedback regarding this and I am aware that this is a common pain point on v2. I 100% hear you and it's still in the back of my mind for my next Laravel Actions sprint.

For now, the best thing to do would be to create and run a validator directly in the handle method based on the arguments received. Something like:

```php
public function handle (string $title, string $content)
{
    $validator = Validator::make(compact('title', 'content'), [
        'title' => ['required'],
        'content' => ['required', 'min:10'],
    ]);

    // ...
}
```

You would then need to ensure you do not implement the following methods if you don't want to trigger the controller validation as well. This is the logic the `ControllerDecorator` uses to trigger validation.

```php
protected function shouldValidate()
{
    return $this->hasMethod('authorize')
        || $this->hasMethod('rules')
        || $this->hasMethod('withValidator')
        || $this->hasMethod('afterValidator')
        || $this->hasMethod('getValidator');
}
```

I realise that this aspect of v2 is a bit tricky at the moment but it was a crucial point for allowing actions to be more flexible and adapt to any implementations rather than relying on a unified bag of attributes.

That being said, I've got some thoughts around a optional trait that would allow authorization and validation outside controller land as well.

I hope this helps. 🍀

**Comment by anyb1s** [comment]
Thank you for the quick reply, it was helpful! This is my current approach as well, wasn't sure if that was the way to go.
Happy to hear you're planning an update around this. 

P.S. this package is awesome! 💯

**Comment by anyb1s** [comment]
OMG This is awesomeeee! I tried different approaches to migrate my actions to figure out how to do the validation/authorization. This is a amazing. I have like 100+ actions and will definitely easy up the migration and to utilize to power of v2.

**Comment by artjomzab** [comment]
@anyb1s livewire needs the rules property for validation and for data binding. Do you have the same rules in the livewire component and the action or did you find a solution, where you define the rules just once?

**Comment by artjomzab** [comment]
@anyb1s can you show an example how you're using actions with livewire to validate form data? For me validation works fine, however the magic of livewire's validate method is not executed. Because of that the error messages in the view are not updated properly. On first submit the error message is shown. On the second submit with valid data the error message is still present.

What I've tried:

```
public function handle(Note $note, array $attributes = []): void
{
    $this->set('note', $note)->fill($attributes);
    $this->validateAttributes();
}
```

I am calling this from a livewire component:

```
public function save(): void
{
    UpdateNote::run($this->note);
}

```
I would love to have the validation logic in the action, since its business logic. 

What I can do is to validate a second time after running the action in the livewire component or use realtime validation:

```
public function updated($field): void
{
     $this->validateOnly($field);
}
```

to update the error messages.

@lorisleiva would love to hear your opinion.

**Comment by lorisleiva** [comment]
Hey @artjomzab 👋  I don't actually use Livewire in any of my projects at the moment so I'm not really the best person to answer that but I'd love to hear what others are doing to combine Laravel Actions and Livewire components. Maybe opening a new discussion might bring more visibility to the subject than a closed issue. 🙂

**Comment by artjomzab** [comment]
@lorisleiva @anyb1s okay, let's continue this discussion here https://github.com/lorisleiva/laravel-actions/discussions/125
